function t2f_addMenus(cmd)
switch cmd
    case 'main'
        %% get figure handle
        hFuzzy=findall(0,'tag','fuzzyt2');
        
        %% File
        fileHndl=uimenu(hFuzzy,...
            'Label','File');
        h = uimenu('Parent',fileHndl, ...
            'Label', 'New FIS...');
        %         uimenu('Parent',h, ...
        %             'Label', 'Mamdani', ...
        %             'Tag', 'newmamdani',...
        %             'Callback','');
        uimenu('Parent', h, ...
            'Label', 'Sugeno', ...
            'Callback','');
        % File submenu item Import
        h = uimenu('Parent', fileHndl,'Label', 'Load', ...
            'Separator','on');
        uimenu('Parent',h,'Label', 'From File...', ...
            'Tag', 'openfis',...            
            'Accelerator', 'O', ...
            'Callback','fuzzytype2(''loadfile'')');
        uimenu('Parent',h,'Label', 'From Workspace...', ...
            'Tag', 'openfis',...
            'Callback','fuzzytype2(''loadworkspace'')');
        % File submenu item Export
        h = uimenu('Parent', fileHndl,'Label', 'Save');
        uimenu('Parent',h,'Label', 'To Workspace...', ...
            'Accelerator', 'T', ...
            'Callback', 't2f_savews');
        uimenu('Parent',h,'Label', 'To File...', ...
            'Tag', 'save',...            
            'Accelerator', 'S', ...
            'Callback','t2f_save');
        % File submenu item Print
        %         uimenu(fileHndl,'Label', 'Print', ...
        %             'Separator','on', ...
        %             'Callback','');
        %         % File submenu item Close
        %         uimenu(fileHndl,'Label', 'Close', ...
        %             'Separator','on', ...
        %             'Callback','');
        
        %% Edit
        h1 = uimenu(hFuzzy, ...
            'Label','Edit');
        %         uimenu(h1, ...
        %             'Callback','', ...
        %             'Label','Open MUT');
        h2 = uimenu('Parent', h1,'Label', 'Add Variable...');
        uimenu(h2, ...
            'Tag','menu_input',...
            'Callback','fuzzytype2(''addvar'',''input'')',...
            'Label','Input');
        uimenu(h2, ...
            'Tag','menu_output',...
            'Callback','fuzzytype2(''addvar'',''output'')',...
            'Label','Output');
        %         uimenu(h1, ...
        %             'Callback','', ...
        %             'Label','Remove Selected Variable');
        %         uimenu(h1, ...
        %             'Callback','', ...
        %             'Label','Membership Functions...');
        uimenu(h1, ...
            'Callback','ruleedit2', ...
            'Label','Rules...');
        
        
        %% View
        h1 = uimenu(hFuzzy, ...
            'Label','View');
%         uimenu(h1, ...
%             'Callback','', ...
%             'Label','Rules');
        uimenu(h1, ...
            'Callback','t2f_viewSurface', ...
            'Label','Surface');
        
    case 'mfedit'
        %% get figure handle
        hFuzzy=findall(0,'tag','mfedit2');
        
        
        %% Edit
        h1 = uimenu(hFuzzy, ...
            'Label','Edit');
        uimenu(h1, ...
            'Callback','mfedit2(''addmfs'')', ...
            'Label','Add MFs...');
%         %         uimenu(h1, ...
%         %             'Callback','',...
%         %             'Label','Add Custom MFs...');
%         %         uimenu(h1, ...
%         %             'Callback','mfedit2(''removemf'')',...
%         %             'Label','Remove Selected MF');
        uimenu(h1, ...
            'Callback','mfedit2(''removeallmfs'')', ...
            'Label','Remove All MFs');
%         %         uimenu(h1, ...
%         %             'Callback','', ...
%         %             'Label','Membership Functions...');
%         %         uimenu(h1, ...
%         %             'Callback','', ...
%         %             'Label','Rules...');
%         
%         
%         %% View
%         h1 = uimenu(hFuzzy, ...
%             'Label','View');
%         uimenu(h1, ...
%             'Callback','', ...
%             'Label','Rules');
%         uimenu(h1, ...
%             'Callback','t2f_viewSurface', ...
%             'Label','Surface');
%         
        
        
end
